### ISSUE TITLE
"send reminder only for students who have not answered" checkbox?

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1038]
to avoid spam?

**Comment by mluukkai** [comment]
what the checkbox should do? the reminder is sent only to those who have not answered

<img width="566" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/a3eb33c7-6087-4283-9385-b448e7300f20">

**Comment by Veikkosuhonen** [comment]
Closing because maybe a misunderstanding. Please open with better explanation
