### ISSUE TITLE
Remember questions and settings from previous course

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#1048]
I teach the same courses several times in the year and, for each course, I add an additional question ("yleisarvosana kurssille") and make all feedback fields public. This is a lot of unnecessary clicking and sometimes I forget to make the fields public. It would be better that the questions and settings would be automatically copied from the previous course when a new course is created in the feedback system.

**Comment by mluukkai** [comment]
there will be later a proper implementation for this issue (= opintojaksokohtaiset kysymykset) by Univ of Tampere
