### ISSUE TITLE
question ordering clarification

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1078]
where does the question order come here

https://norppa.helsinki.fi/targets/72438142

(why koulutusohjelma question after course specific questions)

**Comment by Keskimaki** [comment]
Both organization and university level open questions are placed last in question ordering

So this is working as specified at https://github.com/UniversityOfHelsinkiCS/palaute/blob/6c16cc478e8a056932d3f7097d020baa73dfc59c/config/default.js#L203C7-L203C7
