### ISSUE TITLE
only small portion of registered students in CUR

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1093]
https://norppa.helsinki.fi/targets/72482660/feedback

<img width="1036" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/c4000440-a36b-4403-9b4b-e726475ff1e5">

**Comment by Keskimaki** [comment]
Number is wrong because of old cache data. Otherwise fixed by rerunning Importer after previous crash
