### ISSUE TITLE
koulutusohjelman kysely: result broken in some cases

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1112]
https://norppa.helsinki.fi/targets/75652312/results

<img width="660" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/e136fde6-d0e0-4d52-abcb-6e6e9ee6267c">

One student was added to this course after it started. 

Pretty sure that miko has given the answer but it is gone:

<img width="1544" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/cf616444-89f1-4f37-8b4b-b1db8e32ec53">

- [ ] ensure that all worx after a kysely edited

**Comment by HRemonen** [comment]
This is because the UFBT's are deleted and also the FBT on edit and new FBT is created.

![Screenshot from 2023-11-13 10-41-00](https://github.com/UniversityOfHelsinkiCS/palaute/assets/81435393/ddb48917-4fb3-4db3-aa25-de639abdc7ad)
