### ISSUE TITLE
palaute can be given by admin (in certain cases)

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1120]
when a new kysely created (no questions added), this view is opened 

<img width="1321" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/f3b95161-4cc5-444e-aea9-9c72ff906009">

and by pressing the button a answer is saved (despite the admin is not among the answerees)

**Comment by HRemonen** [comment]
This is only for admin users (Toska) and is perhaps useful for debugging or whatever.
