### ISSUE TITLE
fix logs

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1150]
"remarkable" changes should be shown

now broken

<img width="1208" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/79689096-684b-46ba-b785-c27acba205ed">

<img width="1369" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/521aa529-8eac-4b69-a3c2-bdf643b5fcdb">

Some issues still:

duplicate & delete => useless publicity change message

**Comment by Veikkosuhonen** [comment]
Dupe: already working on #1142
