### ISSUE TITLE
Nav bar is clipping on narrower screens and thus is unusable

### ISSUE THREAD

**Issue by HRemonen** [UniversityOfHelsinkiCS/palaute#1172]
For example on screen width 1024 the following issue arises:

![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/81435393/feb33f70-4a3e-4015-a01f-70e94c4bbd3e)

Also the nav bar is not scrollable if the screen width is wider than the mobile check but narrower than 1024px and thus some of the navigations are not usable:

![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/81435393/93f8e8a7-de9d-44c9-8de1-81ebc5dbf863)

**Comment by A-4-Atom** [comment]
Can you assign it to me? I'll try fixing it. @HRemonen

**Comment by ketansahugit** [comment]
Hi, I would like to work on this issue but I require ID & Pass to login to the site and see the UI where the bug is. could you help me here?

**Comment by HRemonen** [comment]
This issue is pretty much only for admin users and will not be worked on

**Comment by ketansahugit** [comment]
@HRemonen I'm guessing most of the issues are admin only because they have the access of id pass? if not let me know as i'd like to contribute to this repository in the future.
