### ISSUE TITLE
Wrong number of students in feedback results page

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#1184]
117 students out of 116 students have given feedback?

![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/901299/07df4897-cef5-4ee2-bae5-6d8498e94d77)

By the way, it is not clear what the two numbers (117/116) represent, because the total number of (registered?) students is larger (153 at the moment).

![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/901299/ae3e8113-52d2-44c7-8b33-bf97ce662d3a)

**Comment by pllk** [comment]
In the course summary page there is yet another number of students (134 at the moment).

![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/901299/6e5abe08-7393-4085-b74e-cf8c2969814f)

**Comment by Veikkosuhonen** [comment]
Can't repro this exactly anymore, something to do with cache flakyness & some other temp issues in our data pipeline. Initial fix is to
- [ ] Add hover text to the chip which explains that it is "feedbacks given / students"

We'll try to investigate when this cache inconsistency happens...

**Comment by Veikkosuhonen** [comment]
#1192
