### ISSUE TITLE
Fix anon when less than 5 enrolled

### ISSUE THREAD

**Issue by Veikkosuhonen** [UniversityOfHelsinkiCS/palaute#1191]
[norppa.helsinki.fi/targets/19664219/results](https://norppa.helsinki.fi/targets/19664219/results
)
- [x] Check how many courses affected (less than 5 participants)
- [x] check how many courses had the problem (only 1 participant who had given the feedback)
- [x] Fix this shit
- [x] Make configurable?
- [x] collect the money

<img width="185" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/39f32a03-5f41-4ff4-ac30-69971d82ed4b">

**Comment by Keskimaki** [comment]
47904 visible feedback targets in db
13941 have some feedback
389 of those have less than five students
270 have only one feedback given
