### ISSUE TITLE
Undefined response time in logs

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/palaute#1218]
what is this 
{"level":2,"userId":"<tunnus>","method":"GET","url":"/api/feedback-targets/for-student","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","message":"GET /api/feedback-targets/for-student **undefined - undefined** ms"}
should be:
{"level":2,"userId":"<tunnus>","method":"GET","url":"/api/ping","status":"204","responseTime":"0.333","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","message":"GET /api/ping **204 - 0.333 ms**"}

ps. Olen sanaton

**Comment by HRemonen** [comment]
This might be because of UH login session time out. Norppa did not handle that well enough previously, but after introducing the unfuck-spa-headers or whatever the library is, this might be fixed. Dunno - not enough information to go on here...
