### ISSUE TITLE
TUM-3243: This feedback is disabled??

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1248]
Norppa states:

TUM-3243: This feedback is disabled

https://norppa.helsinki.fi/targets/72484415/results

although handle is clear @:

https://norppa.helsinki.fi/organisations/100-M001/settings

**Comment by Veikkosuhonen** [comment]
These numbers also dont seem to add up 
![image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/54055199/b9bc3c7d-1641-413c-b386-c6ea40bc8294)
