### ISSUE TITLE
Enrolments SISU vs NORPPA differs

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1276]
SISU:
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/hy-opt-cur-2324-16b6faf1-e3c1-4929-846d-911d4f91d4ec/enrolment/enrolled

20 students

NORPPA:
https://norppa.helsinki.fi/targets/74070660/students-with-feedback

5 students

**Comment by mluukkai** [comment]
solved, will be fixed at monday morning when importer is rerun
