### ISSUE TITLE
INTERIM FEEDBACK FIX:  MUOKKAA VÄLIPALAUTTEEN KÄYNNISSÄOLOAIKAA

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1287]
"MUOKKAA VÄLIPALAUTETTA" -> MUOKKAA VÄLIPALAUTTEEN NIMEÄ/KÄYNNISSÄOLOAIKAA

also in english:

"EDIT FEEDBACK PERIOD" -> "EDIT INTERIM FEEDBACK NAME/PERIOD"

![2024-05-22_NRPP_interim_fix](https://github.com/UniversityOfHelsinkiCS/palaute/assets/43775188/b3caa0eb-780a-432b-9b6c-79a7b3cbf382)

**Comment by HRemonen** [comment]
This is no longer relevant
