### ISSUE TITLE
Results page broken after updating counter feedback

### ISSUE THREAD

**Issue by HRemonen** [UniversityOfHelsinkiCS/palaute#1315]
When a counter feedback has been given and the teacher goes to edit the counter feedback the feedback target loses its student count completely which results in the following behaviour:

![Image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/81435393/f88bce5b-4152-4e25-9767-6a75f47ca47d)

## How to repro
- Go to a feedback target which has counter feedback
- Check the results page that the results are shown
- Go to edit the counter feedback and save the new new feedback
- Go to the results page
- Reload the page and everything works again

## How to fix
- Probably something to do with the cache so check if the queries are invalidated after counter feedback
- Perhaps it will be more stable after the feedback count and student counts are fetched from the summary object rather than the feedback target object. See #1227 for further information.

**Comment by tfhuhtal** [comment]
![Image](https://github.com/user-attachments/assets/dfc43e4b-056a-4460-8225-105c1708ac7a)

**Comment by tfhuhtal** [comment]
Problem is isolated to backend!
