### ISSUE TITLE
study programme right should NOT provide visibility to tdk level

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#1321]
eg klemstro sees stuff directly under matlu

<img width="1086" alt="image" src="https://github.com/UniversityOfHelsinkiCS/palaute/assets/523235/11cf285f-f307-44c8-b0ad-018e62aa4bb0">

- [ ] do the fix

**Comment by HRemonen** [comment]
## Investigation

In the summary access utility function [getSummaryAccessibleOrganisationIds](https://github.com/UniversityOfHelsinkiCS/palaute/blob/58d80e26618b4c08e872fcff053a4f48c93c4b01/src/server/services/summary/access.js#L3) Access is also given to the parent organisation which cause these issues I guess.

However if this access is not given the tree-like structure is omitted from the summary page - if that matters to someone.

![Image](https://github.com/UniversityOfHelsinkiCS/palaute/assets/81435393/e30a551e-adc1-40a5-885c-a524530dffa1)

**Comment by HRemonen** [comment]
This issue is fixed by TAU changes
