### ISSUE TITLE
KIK-414 numbers do not match

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1350]
This link should take to the first view:
https://norppa.helsinki.fi/organisations/400-K003/summary?startDate=2022-08-01&endDate=2023-07-31&sortBy=feedbackCount&order=desc

![Image](https://github.com/user-attachments/assets/3e65f2ce-c92e-47be-8028-285b23459797)

When cliking, numbers do not match (here):

![Image](https://github.com/user-attachments/assets/61e22e5a-09e3-4f9d-86a9-124c91fc6ec9)

**Comment by HRemonen** [comment]
Duplicate of #1323
