### ISSUE TITLE
Teacher should receive counterfeedback-mail her/himself too as a reminder

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1378]
When adding counterfeedback & sending it via email to students, teacher should receive it too (via email).

**Comment by HRemonen** [comment]
## Specification

Do we want the user to opt-out from this behaviour? If we do we have to consider cases where we have multiple teachers:
- One teacher cannot decide for all
- Each teacher has their own choice -> It gets pretty wild when there are sometimes a lot of teachers. Plus how do the teachers coordinate this among each other before sending the email
