### ISSUE TITLE
SISU groups vs. Norppa groups - fix difference in behaviour

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1380]
SISU:
student can choose between one to many groups

EXAMPLE:
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/hy-opt-cur-2425-68feac15-9b90-4ec7-ad91-0275f97e5f5b/enrolment/enrolled

NRPP:
student can choose only one group

EXAMPLE:
https://norppa.helsinki.fi/targets/82145369/edit

This should consisent,

**Comment by HRemonen** [comment]
Duplicate of #1379
