### ISSUE TITLE
DENT-408 unstable? (and MED-518?)

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#1391]
2024-11-10:

_"Hei,

Muokkasin Norppa-palautetta: lisäsin kysymyksiä ja asetin palautteen alkamisajankohtaa aikaisemmaksi kuin mitä se oli automaattisesti asetettu. Nyt sain opiskelijalta palautetta, että Norppa-palautesivu ei toimi. Hän oli kokeillut sekä tietokoneella että puhelimella. Missähän on nyt ongelma?
"_

11-12-2024_

_"Hei!

Yritän antaa palautetta kurssista DENT-408, mutta Norppa herjaa joka kerta samaa ongelmaa (kuvakaappaus alla, punainen ruutu alareunassa). Mitä teen?
Olen kirjautunut sisään HY-tunnuksilla onnistuneesti, olen yrittänyt antaa palautteen eri laitteilla ja eri selaimilla (kännykkä, työläppäri ja vapaa-ajan läppäri / Duckduckgo, Chrome, Edge).
"_

PUNAINEN: "jotain meni pieleen"

**Comment by HRemonen** [comment]
https://norppa.helsinki.fi/targets/81484332/feedback

**Comment by HRemonen** [comment]
The problem lies from [this commit](https://github.com/UniversityOfHelsinkiCS/palaute/commit/d4df64fb70d504437c6e8d1679e2f03f17790cd4) where the highest access status is tried to return. However this broke the old logic, which checked the student status first and returned it before anything else.
