### ISSUE TITLE
Missing "selected" style in navbar summary link

### ISSUE THREAD

**Issue by HRemonen** [UniversityOfHelsinkiCS/palaute#1409]
Once navigating to the course summary page from the navbar the link is missing the selected state:

![Image](https://github.com/user-attachments/assets/e9cc1d23-eeb7-451a-89a1-ce0fd40ee7e0)

HOW IT SHOULD LOOK LIKE (see Kyselyni)

![Image](https://github.com/user-attachments/assets/15f32863-c58b-40a6-b40e-99db57ab1474)

**Comment by BigBen-7** [comment]
hey Rem, can this be assigned to me?
