### ISSUE TITLE
Have different page title on different pages

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#148]
The <title> of every page in the system is "Palaute" which is not good.

**Comment by Jakousa** [comment]
Is "Palaute" not good or the fact that the page title does not change not good?

**Comment by pllk** [comment]
I think "Palaute" is never good (it is too general), but the most important thing is that the title should change (for example, if the feedback from a course is shown, the name of the course should appear in <title>).

**Comment by Jakousa** [comment]
We changed "Palaute" to "Kurssipalaute" to reflect the main purpose of the app. The automatic changing requires a bit more work. I'll change the issue title.
