### ISSUE TITLE
vastausten näkyvyys opiskelijoille

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#151]
tarvitaan ratkaisu sille voidaanko kaikki tai ainakin HY-tasoset määritellä by default kaikille näkyviksi tai voiko esim TDK-tasosesti määritellä pakkonäkyvyyden, jolloin riittää että opetusvaradekaani käy laittamassa _show all_

jos vastaukset eivät by default näy, on uhkana se, että suurin osa opettajaista jättää laittamatta näkyvyyden ja opiskelijoiden into palautteen antamiseen vähenee

**Comment by kurhila** [comment]
Tämä näkyvyys on se keskeisin ONEn 17.6. kokouksessa päätettäväksi tuleva asia. Itse olen sillä kannalla, että kurssipalaute pyörisi jopa opettajasta riippumatta. Silloin sen olisi lähtökohtaisesti oltava suhteellisen avointa asianosaisille. Asianosaisia ovat: kurssin opiskelijat, kurssin opettajat, kurssin opettajien esihenkilöt (aina rehtoriin saakka), kurssin koulutusohjelman johtoryhmä ja koulutusohjelmaan kytkeytyvä opetusvaradekaani tai -dekaanit.

Koekäyttövaiheessa eli ennen 17.6. näkyvyyden kanssa voi eksperimentoida huoletta eli näkyvyyden voi laittaa maksimiin, ja katsoa että mitä tapahtuu. Omasta mielestäni opiskelijalle voisi hyvin näyttää kurssin numeroarvosanapalautteiden keskiarvot sen jälkeen, kun hän on oman palautteensa antanut. Avovastauksia ei voi näyttää, koska niissä voi olla henkilöarvioita (jotka ovat Suomen lain mukaan ykstyisyydensuojan piirissä myös työelämässä).
