### ISSUE TITLE
possibility for koulutusohjelma to disable survey for some courses

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#270]
NOTE: Change courses to be disabled by default and add the option to then enable the course with course code or somethink

![image](https://user-images.githubusercontent.com/523235/122355149-5a10f880-cf5a-11eb-9ff2-0a6d4670144a.png)

In practice: do a "list of courses" -view for each tiedekunta and there a switch for disabling all instances of that course for being surveyed

order courses by coursecode

navigation to page from 
![image](https://user-images.githubusercontent.com/523235/122355795-dd324e80-cf5a-11eb-8a6c-46236fc0d31a.png)

**Comment by Kaltsoon** [comment]
Needs migration so that all courses are disabled by default:

```
UPDATE organisations
SET disabled_course_codes = ARRAY(
SELECT course_units.course_code
FROM course_units
INNER JOIN course_units_organisations ON course_units.id = course_units_organisations.course_unit_id
WHERE course_units_organisations.organisation_id = organisations.id);
```
