### ISSUE TITLE
Weird time range in main title

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#299]
![image](https://user-images.githubusercontent.com/901299/123639679-1d31e500-d829-11eb-81ff-f0e13c7a40cb.png)

The main title shows that the time range of the course is between 10.05.2021 and 19.06.2021. However, when I open the course, there are actually two instances and only the time range of the first instance is that in the main title.

**Comment by mluukkai** [comment]
good point, in this kind of situations, both dates should be in main header

if (and when) start and end are in same year, format could be a bit more breaf:
10.5.-19.6.2021 instead of 10.5.2021-19.6.2021

**Comment by LeoVaris** [comment]
I removed the date. We cannot show both dates, because there can be 1-n realisations (not 1-2).
