### ISSUE TITLE
Tradition of Weboodi palaute email spam continues

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#389]
I just got a large amount of unwanted emails:

![image](https://user-images.githubusercontent.com/901299/132185033-15bfdb4b-92a3-4eb5-9980-29c435d0b9dc.png)

Each message asks me to give feedback, while I'm the teacher of the course:

![image](https://user-images.githubusercontent.com/901299/132185163-cc9466e9-801a-4958-a53b-7cc764a4fc54.png)

**Comment by mluukkai** [comment]
Shit happened. Will be fixed in a future release, see https://github.com/UniversityOfHelsinkiCS/palaute/issues/395
