### ISSUE TITLE
2021-09-14 user case: feedback on feedback

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#423]
Arviointi mittasi oppimistani *: _oppimista ei opiskelija pysty kuvaamaan emmekä sitä halunne? Pitänee olla ”osaamistani”. Lisäksi tämä ohjaa opiskelijoita ajattelemaan vain tenttejä, joita ei ole ollenkaan kaikilla opintojaksoilla. Siinä mielessä onkin hyvä, että vaihtoehtona jo on myös eos. Tai voisiko olla, ettei olisi pakollinen vastata?_

Työmäärältään opintojakso oli *: _Tätä tuskin haluamme kuulla, vaan haluamme opiskelijan vertaavan SUHTEESSA OPINTOPISTEISIIN. Eli ”Opintojakso oli opintopisteisiin nähden työmäärältään…”. Jos sitä ei ole mainittuna, vastaus on lähinnä fiilistelyä sen pohjalta, miten tärkeänä opintojaksoa yleensäkään piti, tai sen mukaan, oliko nukkunut yönsä hyvin tmv._ 

Muita huomioita: tämä harvoin aktivoi vastaamaan. Sen sijaan esim.: _Mikä opintojaksolla toimi? Mitä parannusehdotuksia sinulla on?_ 

LISÄKSI:

_-Jokaisen HY opintojakson lopussa aukeaa itsestään, pyytämättä, avautumisaikaa ei voi ennalta määritellä: tämä vähentää opiskelijapalautteen saamista eli toivottavasti muuttuu vielä. (vastauksena ei ole se, että opettaja voi itse käydä klikkaamassa sen auki samalla kun vetää tuota opetustaan…)
-QR-koodi, linkki opiskelijoille opetuksen aikana (ei esim. aamulla s-posti Norpalta) tmv. olisi se tapa, jolla oikeasti viimeisen opetuskerran lopussa palautetta voisi saada mahdollisimman paljon. 

-Näkyy ja on muokattavissa jokaisen kurssin opettajan toimesta: tämä on haaste, koska ainakin nyt itse olen palautteen muokkaajana yli 20 muun opettajan kanssa parillakin kurssilla, joiden palautteen eikä ainakaan palautelomakkeen muokkausoikeuden oikeastaan olisi hyvä tulla minulle.
- Tuo liittynee ehkä siihen, että kursseille on lisätty lukujärjestystoimintojen vuoksi kaikki opettajat, ja silloin palautelomakkeetkin ovat kaikille auki.
-> tutkitusti taitaa johtaa siihen, etteivät opiskelijat uskalla/ kehtaa antaa täysin rehellistä palautetta, kun näkyvyys on isolle joukolle opettajia ja tdk:n väkeä -> harmi!

-Voisiko olla mahdollista vaihtaa kysymysten järjestystä? Se osoittaisi myös opiskelijoille, että palautelomakkeella on merkitystä, se on harkittu, ja se mahdollistaisi erityisen tärkeiden jaksokohtaisten kysymysten nousemisen keskiöön -> palautteesta isompi hyöty

Tsemppiä kehittämistyöhön ja syksyynne!_

**Comment by mluukkai** [comment]
QR-koodi, linkki opiskelijoille opetuksen aikana (ei esim. aamulla s-posti Norpalta) tmv. olisi se tapa, jolla oikeasti viimeisen opetuskerran lopussa palautetta voisi saada mahdollisimman paljon.

**tämähän on jo olemassa. kurssisivulla linkki + opettaja voi sen linkin toimittaa vaikka kotiovelle**
Jokaisen HY opintojakson lopussa aukeaa itsestään, pyytämättä, avautumisaikaa ei voi ennalta määritellä: tämä vähentää opiskelijapalautteen saamista eli toivottavasti muuttuu vielä. (vastauksena ei ole se, että opettaja voi itse käydä klikkaamassa sen auki samalla kun vetää tuota opetustaan…) 

**ei pidä paikkaansa, ite voi määritellä alkamis- ja loppumisajan **

Voisiko olla mahdollista vaihtaa kysymysten järjestystä? Se osoittaisi myös opiskelijoille, että palautelomakkeella on merkitystä, se on harkittu, ja se mahdollistaisi erityisen tärkeiden jaksokohtaisten kysymysten nousemisen keskiöön -> palautteesta isompi hyöty

**voi muuttaa mutta ei HY-tasoa. siksi koska se on HY-taso**

**Comment by tttriple** [comment]
2021-09-15 mail/answer sent
