### ISSUE TITLE
käyttöohje outdated

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#435]
dates are wrong

- mail to students **when feedback opens** (it is by default at the course end date but can be changed)
- reminder to teacher **one week before feedback opens** 

_teacher can manually open and close the course feedback form on desired dates._

this is not accurate anymore... teacher can set the opening and closing dates

![image](https://user-images.githubusercontent.com/523235/133970657-6a7e62f6-9a30-45b3-b26e-fb6c5d6c34e4.png)

**Comment by tttriple** [comment]
@mluukkai please check the fixed käyttöohje and close if all's set.
