### ISSUE TITLE
Check if SISU has applicable "role" besides vastuuopettaja/opettaja to use in Norppa

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#448]
Currently only teacher of a certain course can edit/add "course questions" to Norppa. And certain programs are adding kosus as teachers to be able to do this....

not good.

Check if SISU has applicable role where kosus (etc.) can be added and inherit that role to NORPPA.

**Comment by mluukkai** [comment]
yes. **hallintohenkilö** is inherited in norppa
