### ISSUE TITLE
no access to avovastaus despite BIG BOSS

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#461]
![image](https://user-images.githubusercontent.com/523235/136159642-2ea62ece-2043-4d2b-8bcb-a619facb104d.png)

https://coursefeedback.helsinki.fi/course-summary/MED-200

![image](https://user-images.githubusercontent.com/523235/136159571-4f28c2e8-4f8b-4635-8683-a30b328f4090.png)

**Comment by tttriple** [comment]
This is how its done:

![2021-10-06_Norppa_vs_tilannekuva](https://user-images.githubusercontent.com/43775188/136160697-d947589a-f2f8-4b91-b572-0c6426ee2ee9.JPG)
