### ISSUE TITLE
Invalidate cache after giving feedback

### ISSUE THREAD

**Issue by LeoVaris** [UniversityOfHelsinkiCS/palaute#476]
Now when I give feedback to course X, and go back to the list of feedbacks that I haven't given, the course X is still there. I guess this would be fixed by invalidating the cache once you give feedback. 

As of 10.1, this seemed to be fixed already or at least I couldn't reproduce the bug.

**Comment by Veikkosuhonen** [comment]
watafak, its been done for over a year
