### ISSUE TITLE
what happens and *should happen* when course is updated after feedback is already collected?

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#517]
_Opintojakso MED-315 pidettiin syksyllä 15.9. - 1.10.
Tästä palautteet kerättiin ja vastaukset näkyivät Norpassa.
Nyt tuli tarve lisätä tähän vielä 1 opetustapahtuma, joka on huomenna 25.11.
Palautelomake on siirtynyt uudelleen Käynnissä olevat kurssit-kategoriaan.
Palautetta EI siis ole enää tarkoitus kerätä uudelleen._

Lisätyn tapahtuman (25.11.) jälkeen kurssin tiedot "väärin": näyttää kuten palautetta ei olisi kerätty. Eli mitä tehdään jatkossa näissä keisseissä.
![MED-315](https://user-images.githubusercontent.com/43775188/143388954-7b8ad950-ed72-4dc1-ba87-e02cdaf27bc6.JPG)

**Comment by mluukkai** [comment]
new email is not sent to student BUT given feedbacks can be edited
