### ISSUE TITLE
betterment for nonAD avoin users (implement by end of period 3)

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#531]
kaikki opiskelijat eivät ole ilmonneet siinä vaiheessa kun norppa lähettää default-mailin 

tarvitaan mekanismi, joka lähettää myöhään ilmottautuneille mailin palautteesta, esim joka yö edellisenä päivänä ilmonneille.

Technical stuff:

- [x] Add email send status to user feedback target
- [x] Add a migration for the existing feedback targets which have the email sent (to avoid resending emails). Something like "set email send status to true for those user feedback targets where email send status is true for the feedback target"
- [x] Change the way the [updater handles canceled enrolments](https://github.com/UniversityOfHelsinkiCS/palaute/blob/master/src/server/updater/updateStudentFeedbackTargets.js#L93). Can't delete all user feedback targets without feedback, need to also check if email is not send

**Comment by Veikkosuhonen** [comment]
done
