### ISSUE TITLE
pienryhmäopetus & harjoitusryhmät

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#554]
https://coursefeedback.helsinki.fi/targets/1121778/editYllä esimerkki kurssista, jonka kurssirealisaatio "pienryhmäopetus".

  Pystyttekö hakemaan syksyn 2021 osalta lukumäärän, kuinka monta näitä on ollut Norpan palautteenkeruun piirissä.
  Pystyisikö teknisesti palautelomakkeen "jyvittämään" harjoitusryhmä-tasolle? Eli tuolla kurssilla on erikseen vielä 4kpl harjoitusryhmiä.

Huomasin, että kevään 2022 AYO on toteuttanut ryhmät Sisuun erillisinä. Näistä yksi on tässä:
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/otm-b02d0637-27f2-4a1e-8881-cd5f2dc5a7f5/information/basicinfo
Mikä tämän kurssi-realisaation tyyppi on? Pienryhmäopetus?

**Comment by LeoVaris** [comment]
Pystyttekö hakemaan syksyn 2021 osalta lukumäärän, kuinka monta näitä on ollut Norpan palautteenkeruun piirissä.

> Kursseja, voiden tyyppi on "pienryhmäopetus" ja aloituspäivä on 1.8.2021 tai myöhempi löytyy 212 kurssia. 

Pystyisikö teknisesti palautelomakkeen "jyvittämään" harjoitusryhmä-tasolle?

> Tiketti #352 

Mikä tämän kurssi-realisaation tyyppi on? Pienryhmäopetus?

> `course-unit-realisation-type:teaching-participation-online` eli "Verkko-opetus"
