### ISSUE TITLE
KOK-N203

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#569]
SYKSY2021
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/hy-opt-cur-2122-bcc38f91-93a8-4ddf-9c64-436e262ca491/information/basicinfo

KEVÄT2022
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/hy-opt-cur-2122-75a11b2f-399f-4203-b3eb-b1bb2c5b92f0/information/basicinfo

Molemmilla vastuuopettajina:
hy-hlo-112225682
hy-hlo-87432204

Vain jälkimmäinen näkee SYKSY2021 palautteet Norpassa?

**Comment by LeoVaris** [comment]
Tää tais olla jo fiksed?
