### ISSUE TITLE
Not all charts visible on first render

### ISSUE THREAD

**Issue by ollikehy** [UniversityOfHelsinkiCS/palaute#573]
Maybe an issue with either some of the questions being programme level questions? or maybe because of loading times? loading times because admin user loads so much?

Example course https://coursefeedback.helsinki.fi/targets/11668756/results

**Comment by Veikkosuhonen** [comment]
This issue was so epic it eventually fixed itself. Maybe with react 18? 
The example course doesnt have answers to some questions so no charts.
