### ISSUE TITLE
user does not see a course 

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#603]
hy-hlo-1426595

should have access to https://coursefeedback.helsinki.fi/targets/4902908/feedback

the reason is perhaps the fact that this is NOT HY course but organized by yhteistyöoppilaitos ==> user has no staff-bit in shibboleth

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/523235/156143319-cd337d0c-92ad-40f1-baf7-28061a2d9cb6.png">

**Comment by Veikkosuhonen** [comment]
roskiin koska :toimii:
