### ISSUE TITLE
Courses that did not happen: Norppa or Sisu issue?

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#690]
_Hei,
olisiko opettajalla hyvä olla mahdollisuus poistaa Norpasta opintojakso, joka ei lopultakaan toteutunut? Jos tilastoitte vastapalautteen antamista, niin KK-SAK207 Saksan jatkokurssi 2 (CEFR A2) ei koskaan toteutunut, mutta Norppa kaipaa opettajan vastapalautetta tämän kurssin osalta._

**Comment by mluukkai** [comment]
ei löydy näillä tiedoilla kurssia. tarvitaan opettajan nimi
