### ISSUE TITLE
Counter feedback not sent?

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#710]
![image](https://user-images.githubusercontent.com/901299/173231924-ecf1ce2d-e933-46b8-a3e1-6d0cc48a9cfd.png)
The system shows that I haven't sent counter feedback (but I have given it). I don't know how to send it (by the way, it's an old course instance and I haven't seen such a message before).

Fix:
If feedback started before 
![image](https://user-images.githubusercontent.com/54055199/173521800-a5012c34-8636-4631-a8a3-58f4c48609ca.png)
then instead of this
![image](https://user-images.githubusercontent.com/54055199/173522013-dd6d2dfa-1163-4d64-b381-a53cf3ee307a.png)
show this 
![image](https://user-images.githubusercontent.com/54055199/173522081-9fb38364-cf57-424a-baef-5b99bd0061fd.png)

**Comment by Veikkosuhonen** [comment]
This is a bug as in the past "sending" wasn't a thing, so now it shows that. Thx for the issue, we'll fix.
