### ISSUE TITLE
add JATKUVA PALAUTE to Norppa

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#786]
let the s**t pour in

In normal speech:

- Students can give generic textual feedback DURING when the course is running. That is, when `cur.startDate >= NOW >= cur.endDate`.

- Instead of seeing the disabled feedback form, students see just a text box with some additional information. 

- Teacher sees a new tab "Jatkuva palaute". All the jatkuva feedback goes here in a continuous feed.

- Teacher can enable/disable this feature for the course from Jatkuva Palaute tab. (What is the default?)

- Teacher can edit the title and description for the jatkuva palaute text form. (?)

**Comment by mluukkai** [comment]
👍
