### ISSUE TITLE
quick status of course instance

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#80]
Note: as of now sum of given feedbacks is shown, but total amount of students is still a ?

![image](https://user-images.githubusercontent.com/523235/116512777-3540c300-a8d1-11eb-9867-4cfbe5a6266f.png)

**Comment by LeoVaris** [comment]
Seeing the total amount of students who can give feedback is actually not supported in the backend at the moment. It is not a simple change, so most likely this can be considered in the future
