### ISSUE TITLE
Finnish course, feedback in English (?)

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/palaute#800]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/523235/192482038-9c523a3e-7e17-4160-8b06-b4863da7d1e5.png">

I have noticed that many students give feedback in English, while my course is 100% Finnish. For example, at the moment 5 out of 7 entries in Tikape syksy 2022 are written in English which is surprising.

I don't know the reason for this and can't test what happens as a student who gives feedback. Maybe the Norppa user interface for students is in English while the course is in Finnish?

**Comment by Veikkosuhonen** [comment]
This might be because if students dont login with their university account (so called "noad" feature), their UI currently defaults to english. Might be fixable though.

**Comment by Veikkosuhonen** [comment]
We will try to make it so if course has only one teaching language, like yours, the UI defaults to that.
