### ISSUE TITLE
Certain course: different implementation and SISU realisation

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#802]
For example:

Same course, different implementation, different SISU realisation:

independent
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/otm-a994004a-534f-462d-8c09-6b30d0f35f11/information/basicinfo

online teaching
https://sisu.helsinki.fi/teacher/role/staff/teaching/course-unit-realisations/view/otm-9a979840-1994-44bf-ab1e-3ee172c63925/information/basicinfo

Teacher might want both in Norppa. How to handle these cases? Adhoc / neat if?

**Comment by mluukkai** [comment]
change in sisu pls, no shit in norppa
