### ISSUE TITLE
hide studyprogramme tweaks

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#812]
add hover text to hide/show symbol

do not show textbox if none hidden

<img width="275" alt="image" src="https://user-images.githubusercontent.com/523235/193840147-7d766f28-331c-476c-8c63-59c462cf3917.png">

**Comment by Veikkosuhonen** [comment]
Did this: clicking a button in the heading toggles "hiding mode" where all programmes are visible, and the hiding buttons become visible
