### ISSUE TITLE
do not show hours in survey avautuu and sulkeutuu

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#87]
it is enough to have only the date level granularity 

- starts 1.1.2022 => starts 1.1.2022 at 00:00
- ends 31.12.2022 => ends 31.12.2022 at 23:59

![image](https://user-images.githubusercontent.com/523235/116547854-1a377880-a8fc-11eb-86b4-8444309eb792.png)

**Comment by LeoVaris** [comment]
More practical would be:
Ends at 5.5 -> actually ends at 6.5 00:00
