### ISSUE TITLE
Automatic studytrack tags based on course code for KK 

### ISSUE THREAD

**Issue by Veikkosuhonen** [UniversityOfHelsinkiCS/palaute#871]
KK has several language track things, kind of like studytracks. They are well shown in the course codes, so we can automatically infer the studytracks from those and apply them to course realisations.

- [ ] Ask KK for what the "studytracks" are, their names in fi en sv
- [ ] Do the acual shit

**Comment by mluukkai** [comment]
this is shit, kasvatustiede feature takes care of this
