### ISSUE TITLE
Avoimen kurssi not shown 

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#893]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/523235/201092445-77c6e060-8085-4dd1-b6c1-f8e7d8eb964c.png">

but

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/523235/201092307-bc5680b0-0f0b-408b-9086-e28c2c7f1ab6.png">

**Comment by Keskimaki** [comment]
Superseded by  https://github.com/UniversityOfHelsinkiCS/palaute/issues/916
