### ISSUE TITLE
tutkijakoulut ja avoin: miten organisaatioita käytetään

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#900]
_Tässä vaiheessa riittää, että saamme koottua tiedot sovelluksista, jotka käyttävät näitä organisaatiotietoja sekä niistä tarkennukset, mitä koodia käyttävät ja mihin tarkoitukseen_

- [x] document the acual shit

do it like this

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/523235/201860306-6a29e804-fdb6-4531-81cc-ce04c2631752.png">

**Lomake:**
Käytössä IAMit:
- hy-tutkijakoulut-hymy-jory
- hy-tutkijakoulut-dshealth-jory
- hy-tutkijakoulut-yeb-jory
- hy-tutkijakoulut-donasci-jory

Kyseisillä IAMeilla saa lukuoikeudet ko. tutkijakoulun alaisiin tohtoriohjelmiin

**Comment by outisa** [comment]
Oodikone:

Käytöstä löytyy IAMit
-   hy-tutkijakoulut-hymy-jory
-   hy-tutkijakoulut-dshealth-jory
-   hy-tutkijakoulut-yeb-jory
-   hy-tutkijakoulut-donasci-jory

Jory päätteelliset saa oikeuden faculty -näkymään, johon periaatteessa riittää pelkkä grp-oodikone-users oikeus, mutta kaikilla jory ihmisillä tätä ei ole  vaan on grp-oodikone-basics-users.
 
Organisaatiokoodia H930 tai paremminkin  nimeä ja organisaatioid:tä käytetään luokittelemaan onko jokin suoritus tai ilmoittautuminen avoimen järjestämä.

Lisäksi organisaation id:tä käytetään liittämään avoimen järjestämät kurssit avoimen organisaatioon.

**Comment by Veikkosuhonen** [comment]
### Tutkijakoulut

Tutkijakoulujen omia organisaatiotietoja _EI_ käytetä. Niihin kuuluvien tohtoriohjelmien tietoja käytetään.
Käytössä samat IAMit kuin lomake, oodikone (copypastea)

- `hy-tutkijakoulut-hymy-jory`
- `hy-tutkijakoulut-dshealth-jory`
- `hy-tutkijakoulut-yeb-jory`
- `hy-tutkijakoulut-donasci-jory`

Tutkijakoulun jory-IAM antaa lukuoikeuden tutkijakoulun tohtoriohjelmien palautestatistiikkaan ja niiden kurssien julkiseen palautteeseen. 
[Tässä käytetyt ohjelmakoodit tutkijakouluihin kuuluvien tohtoriohjelmien määrittelyyn](https://github.com/UniversityOfHelsinkiCS/palaute/blob/ef70b837766ab2cf79bedac5c4086afe96e1f8b6/src/config/IAMConfig.js#L324)

### Avoin yliopisto

Avoimen yliopiston organisaatiokoodia `H930` käytetään avoimen yliopiston kurssien lukuoikeuksien jakamisessa IAM-ryhmälle
`grp-avoin-johto`. 

Avoimen yliopiston organisaation id:tä `hy-org-48645785` käytetään kurssien jaottelussa avoimen yliopiston kursseihin kurssistatistiikassa.
