### ISSUE TITLE
Handle situtation when username not found

### ISSUE THREAD

**Issue by Veikkosuhonen** [UniversityOfHelsinkiCS/palaute#943]
Currently this leads to a loop of page refreshes and hundreds of 404 being made. Instead show a useful error message to user: "Käyttäjääsi ei löydy. Jos olet vastikään luonut yliopiston AD-käyttäjän, voit joutua odottamaan seuraavaan päivään asti."

voi myös johtua siitä että käyttäjä ei ole sisussa jolloin mikään ei auta

**Comment by HRemonen** [comment]
extremely rare - mluukkai
