### ISSUE TITLE
muistutus lähetetty date fakd?

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/palaute#965]
most likely fakd

https://coursefeedback.helsinki.fi/targets/37221267/results

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/523235/210316963-9a00f8c0-65ab-4a02-b364-645a84baf868.png">

**Comment by Keskimaki** [comment]
![image](https://user-images.githubusercontent.com/87322574/211265335-96981fd2-5373-4467-a985-14d69e699bf7.png)
