### ISSUE TITLE
workaround for non-SISU students to be able to use Norppa?

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/palaute#966]
_"Taas tuli mieleen yksi kysymys koskien kurssipalautelomakkeita:
-	Voivatko kursseille osallistuvat ns. ulkopuoliset osallistujat vastata lomakkeeseen? 

Meillä osalle kursseista osallistuu myös jo valmistuneita eläinlääkäreitä tai eläinfysioterapeutteja yms, jotka eivät ilmoittaudu ollenkaan Sisun kautta eikä heillä ole mitään opinto-oikeuksiakaan vaan he maksavat kursseille osallistumisesta. Niin mietin voivatko hekin vastata palauttekyselyihin?
"_

**Comment by mluukkai** [comment]
tämä tulee toteuttaa HY:n hallinnon tahdon mukaisesti, eli osallistujille tulee antaa joko avoimen yo:n tai erillisopinto-oikeus
